### ISSUE TITLE
Add log function to the calculator

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/node-calculator#1]
## Description

* Add **log** function to the **calculator.js**
* Use that function in **app.js** to demo it
* Run the tests to make sure nothing breaks

**Comment by georgioupanayiotis** [comment]
picking this one!

**Comment by ameerthehacker** [comment]
please goahead

**Comment by georgioupanayiotis** [comment]
what is the command to run the test i did the change

**Comment by ameerthehacker** [comment]
npm run test

**Comment by georgioupanayiotis** [comment]
ok they pass fine, I'm trying to push my branch and open PR and I get 
fatal: unable to access 'https://github.com/ameerthehacker/node-calculator.git/': The requested URL returned error: 403

**Comment by georgioupanayiotis** [comment]
remote: Permission to ameerthehacker/node-calculator.git denied to georgioupanayiotis.

can you assignee me ?

**Comment by ameerthehacker** [comment]
* you need to first fork my repo
* clone it from your account
* push the changes to ur account repo
* create a PR

**Comment by ameerthehacker** [comment]
closing this issue as PR was made and merged
