### ISSUE TITLE
Add cos function to the calculator

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/node-calculator#13]
## Description

* Add **cos** function to the **calculator.js**
* Use that function in **app.js** to demo it
* Run the tests to make sure nothing breaks

**Comment by manisacharya** [comment]
Hello, @ameerthehacker I want to try this.

**Comment by manisacharya** [comment]
This was already done?

**Comment by ameerthehacker** [comment]
Yes a PR has been already made and merged!

**Comment by manisacharya** [comment]
@ameerthehacker I didn't saw any references here, so I was about to send the PR earlier. I have now instead added other functions.
Can you review https://github.com/ameerthehacker/node-calculator/pull/15?

**Comment by ameerthehacker** [comment]
awesome merged it @manisacharya
