### ISSUE TITLE
Add function to illustrate standard deviation

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/node-calculator#16]
## Description

* Add **standard deviation** function to the **calculator.js**
* Use that function in **app.js** to demo it
* Run the tests to make sure nothing breaks

**Comment by prabhumarappan** [comment]
Working on this issue

**Comment by ameerthehacker** [comment]
Yes please goahead

**Comment by OsamaNabih** [comment]
I have submitted a PR

**Comment by ameerthehacker** [comment]
closing this issue as a PR was already made and merged
