### ISSUE TITLE
Add travis for CI

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/node-calculator#2]
## Desription

Add a **travis.yml** file to automatically run the tests whenever someone makes pull request. Initially enable travis on your forked repository and test it. Once you make a PR I will test it from my end.

## Useful Links

https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by NoahvdAa** [comment]
I'll do this.

**Comment by manisacharya** [comment]
Hello @ameerthehacker, I want to try this.

**Comment by ameerthehacker** [comment]
by all means @manisacharya

**Comment by manisacharya** [comment]
@ameerthehacker Have you looked at this? Any issues?

**Comment by ameerthehacker** [comment]
Everything is perfect and I have merged it thanks for contribution!
