### ISSUE TITLE
Add a function to calculate variance

### ISSUE THREAD

**Issue by ameerthehacker** [ameerthehacker/node-calculator#20]
## Description

* Add **variance** function to the **calculator.js**
* Use that function in **app.js** to demo it
* Run the tests to make sure nothing breaks

**Comment by prabhumarappan** [comment]
Working on this issue.

**Comment by ameerthehacker** [comment]
cool please goahead

**Comment by prabhumarappan** [comment]
@ameerthehacker can you please close this issue
